# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# pyright: reportAttributeAccessIssue=false
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import content_service_pb2 as content__service__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in content_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ContentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTranscript = channel.unary_unary(
            "/content.v1.ContentService/ProcessTranscript",
            request_serializer=content__service__pb2.ProcessTranscriptRequest.SerializeToString,
            response_deserializer=content__service__pb2.ProcessTranscriptResponse.FromString,
            _registered_method=True,
        )


class ContentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessTranscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ContentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ProcessTranscript": grpc.unary_unary_rpc_method_handler(
            servicer.ProcessTranscript,
            request_deserializer=content__service__pb2.ProcessTranscriptRequest.FromString,
            response_serializer=content__service__pb2.ProcessTranscriptResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "content.v1.ContentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "content.v1.ContentService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ContentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessTranscript(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # type: ignore[attr-defined]
            request,
            target,
            "/content.v1.ContentService/ProcessTranscript",
            content__service__pb2.ProcessTranscriptRequest.SerializeToString,
            content__service__pb2.ProcessTranscriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
