# Generated by Django 6.0 on 2026-05-08 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_generator", "0004_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector_id", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="note_generator.notepost",
                    ),
                ),
            ],
        ),
    ]
