# Generated by Django 6.0 on 2026-09-17 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_generator", "0005_noteembedding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrievalAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.TextField(help_text="The question as the user asked it."),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        help_text="Retrieval passes made, 1 through 1 + RAG_MAX_RETRIES."
                    ),
                ),
                (
                    "first_grade",
                    models.CharField(
                        choices=[
                            ("SUFFICIENT", "Sufficient"),
                            ("INSUFFICIENT", "Insufficient"),
                            ("UNPARSEABLE", "Unparseable"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "grades",
                    models.JSONField(
                        default=list, help_text="Grade per pass, in order."
                    ),
                ),
                (
                    "rewritten_queries",
                    models.JSONField(
                        default=list, help_text="Queries the grader produced, in order."
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("sufficient_first_pass", "Sufficient on first pass"),
                            ("sufficient_after_retry", "Sufficient after retry"),
                            ("exhausted", "Exhausted retries"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("first_doc_count", models.PositiveSmallIntegerField()),
                ("final_doc_count", models.PositiveSmallIntegerField()),
                ("latency_ms", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieval_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
